### ISSUE TITLE
Canvas License

### ISSUE THREAD

**Issue by Per-Starke** [perstarke-webdev/perstarke-webdev.de-site#3]

**Comment by gernotstarke** [comment]
can I help you with that issues?

**Comment by Per-Starke** [comment]
@gernotstarke  yes please, that'd be great. I don't know if / what / how I should do regarding license, when (after trying it out) I want to publish the canvas as well...

**Comment by gernotstarke** [comment]
one "consulting wisdom": give-away-freely. I'd make it open-source with a liberal license (like creative-commons-sharealike), similar to our arc42 canvas. Put your name & URL in the bottom, maybe add a qr-code.

Publish it on your site AND on dev.to and write a short article (in German) and publish that with a "publisher" (e.g. Informatik-Aktuell) - so you have some official sources where your contribution can be found by many people...

**Comment by Per-Starke** [comment]
@gernotstarke Thank you! I'll do it like that. How do I publish that (when it's more ready and tested, of course) at informatik-aktuell?
