### ISSUE TITLE
Wording suggestion(s)

### ISSUE THREAD

**Issue by gernotstarke** [perstarke-webdev/perstarke-webdev.de-site#30]
# frontpage button: "Der einfache Prozess zu deiner Website"

Vorschlag: Kürzer, und das Wort "Prozess" vermeiden:

- "So einfach kommst Du zu Deiner Website"
- "Deine Website, ganz einfach"

und "Deine" konsistent groß schreiben... momentan mischt Du klein/groß.

# Zitat-Block "Perfekte und einfache Kommunikation" 
-> da solltest Du schon zu schreiben, wer das gesagt hat. Eine "Selbst-Behauptung" finde ich anmaßend.

- Schreib' zumindest drüber "Was Kund:innen über meine Arbeit sagen:"
- Mach' aus den drei Aussagen drei Bullets. Im Absatz mit drei Sätzen geht die einzelne Aussage eher unter.

# Titel darunter "... ist heutzutage absolut essentiell": 

- "absolut" streichen.
- Hilfsverb "ist" durch stärkeres Wort ersetzen

Oder umformulieren:
- Dein Business verdient/braucht eine effektive Online-Präsenz
- Effektive Online-Präsenz als essentieller Bestandteil  

lG aus Köln :-)

**Comment by Per-Starke** [comment]
Danke!!!
